version: '3'

services:
  hbbs:
    image: rustdesk/rustdesk-server:hbbs
    ports:
      - "21115:21115"
      - "21116:21116"
      - "21116:21116/udp"
      - "21118:21118"
    volumes:
      - ./data:/root
    environment:
      - RELAY=Y
      - ENCRYPTED_ONLY=Y
    restart: unless-stopped

  hbbr:
    image: rustdesk/rustdesk-server:hbbr
    ports:
      - "21117:21117"
      - "21119:21119"
    volumes:
      - ./data:/root
    restart: unless-stopped
